// typescript/vue-ts-member/src/MemberRow.vue
<template>
    <tr>
        <td>
            <img :src="member.avatar_url" style="width:100px"/>
        </td>
        <td>
            {{member.id}}
        </td>
        <td>
            {{member.login}}
        </td>
    </tr>
</template>

<script lang="ts" setup>
import { MemberEntity } from './model/MemberEntity'
interface Props{
    member:MemberEntity
}
const props = defineProps<Props>()


</script>

<style scoped>

</style>

// react/member/src/components/MemberRow.tsx
import { MemberEntity } from "../model/member"

const MemberRow = ({member}: {member: MemberEntity}) => {
    return (
        <>
            <tr key={member.id}>
                <td><img src={member.avatar_url} style={{ maxWidth: '10rem' }} /></td>
                <td>{member.id}</td>
                <td>{member.login}</td>
            </tr>
        </>
    )
}
export default MemberRow
